apiVersion: skaffold/v3
kind: Config
metadata:
  name: open-hello-client
build:
  artifacts:
    - image: open-hello-client
      buildpacks:
        builder: paketobuildpacks/builder-jammy-base:latest
        dependencies:
          paths:
            - ./**/*
          ignore:
            - build/**
            - .git/**
            - .gradle/**
manifests:
  rawYaml:
    - deployment.yml
portForward:
  - resourceType: service
    resourceName: open-hello-client
    port: 8080
    localPort: 8080