apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: my-query-parser
spec:
  version: "v1.0.0"
  image: "tony16019/my-query-parser:latest"
  imageCredentials:
    name: push-secret
  build:
    builder: "openfunction/builder-node:latest"
    env:
      FUNC_NAME: "parseQuerySpec"
      FUNC_TYPE: "http"
    srcRepo:
      url: "https://github.com/DuongVu98/openfunction-lab.git"
      sourceSubPath: "open-hello"
      revision: "main"
  serving:
    template:
      containers:
        - name: function
          imagePullPolicy: IfNotPresent
    triggers:
      http:
        port: 8080
        route:
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: "/parse"

---
apiVersion: dapr.io/v1alpha1
kind: HTTPEndpoint
metadata:
  name: "my-query-parser"
spec:
  baseUrl: http://my-query-parser.default.svc.cluster.local
  headers:
  - name: "Accept-Language"
    value: "en-US"
