apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: my-hello-2
spec:
  version: "v1.0.0"
  image: "tony16019/my-hello2:latest"
  imageCredentials:
    name: push-secret
  build:
    builder: "openfunction/builder-node:latest"
    env:
      FUNC_NAME: "helloESM"
      FUNC_TYPE: "http"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/knative/hello-world-node/esm"
      revision: "main"
  serving:
    scaleOptions:
      minReplicas: 0
      maxReplicas: 10
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    triggers:
      http:
        port: 8080
        route:
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /hello

---
apiVersion: dapr.io/v1alpha1
kind: HTTPEndpoint
metadata:
  name: "my-hello-2-entry"
spec:
  baseUrl: http://my-hello-2.default.svc.cluster.local
  headers:
  - name: "Accept-Language"
    value: "en-US"